--create table for raw data
CREATE OR REPLACE TABLE AIRLINE.PUBLIC.PASSENGERS_RAW (
    ID INT, 
    PASSENGER_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    AGE INT,
    NATIONALITY VARCHAR,
    AIRPORT_NAME VARCHAR,
    AIRPORT_COUNTRY_CODE VARCHAR,
    COUNTRY_NAME VARCHAR,
    AIRPORT_CONTINENT VARCHAR,
    CONTINENTS VARCHAR,
    DEPARTURE_DATE DATE,
    ARRIVAL_AIRPORT VARCHAR,
    PILOT_NAME VARCHAR,
    FLIGHT_STATUS VARCHAR,
    TICKET_TYPE VARCHAR,
    PASSENGER_STATUS VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
ALTER TABLE AIRLINE.PUBLIC.AIRLINE_RAW RENAME TO AIRLINE.PUBLIC.AIRLINE_BRONZE;

--create schema for silver layer
CREATE OR REPLACE SCHEMA AIRLINE.SILVER;

--create silver table 
CREATE OR REPLACE TABLE AIRLINE.SILVER.PASSENGER_SILVER_LAYER (
PASSENGER_ID VARCHAR PRIMARY KEY,
FIRST_NAME VARCHAR,
LAST_NAME VARCHAR,
GENDER VARCHAR,
AGE INT,
NATIONALITY VARCHAR
);
--another one
CREATE OR REPLACE TABLE AIRLINE.SILVER.AIRPORT_LOCATION_SILVER_LAYER(
AIRPORT_NAME VARCHAR PRIMARY KEY,
AIRPORT_COUNTRY_CODE VARCHAR,
COUNTRY_NAME VARCHAR,
AIRPORT_CONTINENT VARCHAR
);
--and another
CREATE OR REPLACE TABLE AIRLINE.SILVER.FLIGHTS_SILVER_LAYER(
PASSENGER_ID VARCHAR REFERENCES AIRLINE.SILVER.PASSENGER_SILVER_LAYER(PASSENGER_ID),
PILOT_NAME VARCHAR,
DEPARTURE_DATE DATE,
ARRIVAL_AIRPORT VARCHAR,
FLIGHT_STATUS VARCHAR,
TICKET_TYPE VARCHAR,
AIRPORT_NAME VARCHAR
);
DROP TABLE AIRLINE.SILVER.FLIGHTS_SILVER_LAYER;
--create schema for control (audit log)
CREATE OR REPLACE SCHEMA AIRLINE.CONTROL;

--create table for log
CREATE OR REPLACE TABLE AIRLINE.CONTROL.AUDIT_LOG(
LOG_ID INT AUTOINCREMENT,
TRANSACTION_NAME VARCHAR,
LAYER_TRANSACTION VARCHAR,
TARGET_TABLE VARCHAR,
STATUS VARCHAR DEFAULT 'SUCCESS',
ROW_AFFECTED INT,
LOAD_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

--clear tables silver layers 
TRUNCATE TABLE AIRLINE.SILVER.FLIGHTS_SILVER_LAYER;
TRUNCATE TABLE AIRLINE.SILVER.PASSENGER_SILVER_LAYER;
TRUNCATE TABLE AIRLINE.SILVER.AIRPORT_LOCATION_SILVER_LAYER;
TRUNCATE TABLE AIRLINE.CONTROL.AUDIT_LOG;

--check unicode
SELECT AIRPORT_NAME FROM AIRLINE.SILVER.FLIGHTS_SILVER_LAYER
WHERE DEPARTURE_DATE ='3/11/2022';

--check umlauts
SELECT COUNTRY_NAME FROM AIRLINE.PUBLIC.AIRLINE_BRONZE
WHERE AIRPORT_NAME = 'Gagnoa Airport';

--check right syntax for country like a "Venezuela, Bolivarian Republic of" -> Bolivarian Republic of Venezuela
SELECT COUNTRY_NAME FROM AIRLINE.SILVER.AIRPORT_LOCATION_SILVER_LAYER
WHERE AIRPORT_NAME = 'Caicara del Orinoco Airport';

------time travel 

-- drop table and data first DDL
DROP TABLE AIRLINE.SILVER.FLIGHTS_SILVER_LAYER;
-- restore table
UNDROP TABLE AIRLINE.SILVER.FLIGHTS_SILVER_LAYER;

--create backup table second DDL
CREATE OR REPLACE TABLE AIRLINE.SILVER.FLIGHTS_BACKUP 
CLONE AIRLINE.SILVER.FLIGHTS_SILVER_LAYER
AT(OFFSET => -7200);

--select 5 min ago 1.380.000 rows first DML
SELECT * 
FROM AIRLINE.SILVER.FLIGHTS_SILVER_LAYER 
AT(OFFSET => -60*5);
--1.972.000 rows
SELECT * 
FROM AIRLINE.SILVER.FLIGHTS_SILVER_LAYER ;
--second DML
SELECT * 
FROM AIRLINE.SILVER.FLIGHTS_SILVER_LAYER 
BEFORE(STATEMENT => '01c27b61-0005-0ba9-0001-3c060005451a');