CREATE OR REPLACE SECURE VIEW AIRLINE.GOLD.FLIGHTS_ANALYTIC AS
    SELECT P.PASSENGER_ID,
           P.FIRST_NAME || ' ' || P.LAST_NAME AS FULL_NAME,
           P.GENDER,
           P.AGE,
           P.NATIONALITY,
           F.ARRIVAL_AIRPORT,
           F.FLIGHT_STATUS,
           F.PILOT_NAME
           FROM AIRLINE.SILVER.PASSENGER_SILVER_LAYER P
           JOIN AIRLINE.SILVER.FLIGHTS_SILVER_LAYER F ON P.PASSENGER_ID = F.PASSENGER_ID;

DROP VIEW AIRLINE.GOLD.FLIGHTS_ANALYTIC;
--197.238           
SELECT * FROM AIRLINE.GOLD.FLIGHTS_ANALYTIC
WHERE AGE < 18;
--row policy for age
CREATE OR REPLACE ROW ACCESS POLICY AIRLINE.CONTROL.ADULT_AGE AS (AGE INT) RETURNS BOOLEAN ->
  CURRENT_ROLE() = 'ACCOUNTADMIN' 
  OR age >= 18; 
--masking policy for pilot name if not accountadmin column pilot_name will be ******
CREATE OR REPLACE MASKING POLICY AIRLINE.CONTROL.HIDE_NAME AS (PILOT_NAME VARCHAR) RETURNS STRING ->
CASE 
    WHEN CURRENT_ROLE() = 'ACCOUNTADMIN' THEN PILOT_NAME
    ELSE '*****'
END;

ALTER VIEW AIRLINE.GOLD.FLIGHTS_ANALYTIC
MODIFY COLUMN PILOT_NAME
SET MASKING POLICY AIRLINE.CONTROL.HIDE_NAME;
  
ALTER VIEW AIRLINE.GOLD.FLIGHTS_ANALYTIC 
DROP ROW ACCESS POLICY AIRLINE.CONTROL.ADULT_AGE;

ALTER VIEW AIRLINE.GOLD.FLIGHTS_ANALYTIC 
ADD ROW ACCESS POLICY AIRLINE.CONTROL.ADULT_AGE ON (AGE);
--switch for test row security
USE ROLE USERADMIN;
SELECT CURRENT_ROLE();

